### ISSUE TITLE
Is it possible to reduce the time intervals?

### ISSUE THREAD

**Issue by msslava** [mantisbt-plugins/Calendar#24]
1) When the name of the event contains Cyrillic characters - an error.

2) Is it possible to reduce the time intervals?
For example, 14:00-15:00, 15:00-16:00.

**Comment by brlumen** [comment]
@msslava
Hello!
Do you speak Russian?
Write me directly to my email: igflocal@gmail.com
The error you are talking about looks very strange, since I myself use Cyrillic.

**Comment by msslava** [comment]
Добрый день. Извините, я только увидел, что поддерживается версия, начиная с 2.14.
У меня 2.3. Поэтому скорее всего проблемы. Но, кстати в английской раскладке все работает нормально.
А по второму вопросу можете ответить?

**Comment by brlumen** [comment]
@msslava
1. Since this is an open source project, we will respect other possible participants. I will answer in English (if you want to communicate in Russian - write to me at my email address).

2. Regarding the range of time. Yes you can. Just do it before creating the first event. Otherwise, all events created before changing the parameters will not be displayed.
To change the range, you need in the Calendar.php file, find the variable “stepDayMinutesCount” and replace its value with 1.

**Comment by msslava** [comment]
Ok, many thanks!
